version: '3.8'

services: 
  frontend: 
    container_name: frontend
    ports: 
      - "5173:5173"
    build: 
      context: ./frontend 
      dockerfile: Dockerfile 
    volumes: 
      - ./frontend:/app 
      - /app/node_modules 
    command: npm run dev